[toolchain]
#channel = "nightly-2024-05-01"
channel = "nightly-2025-01-07"

#channel = "nightly-2025-04-14"

#channel = "nightly-aarch64-apple-darwin"
#channel = "stable-aarch64-apple-darwin"
#channel = "nightly-2023-08-21"
#rustc 1.80.0-nightly (f705de596 2024-04-30)
